### ISSUE TITLE
a exe in centos visted cache on windows  with .net 5

### ISSUE THREAD

**Issue by 1009058470** [intersystems-community/developer-community#674]
#### Describe the problem you're observing:
I have make a demo for visted cache on centos and write this demo .
 it work well on my windows machine but on my linux machein it get this error
`
The Error

System.UnauthorizedAccessException: Access to the path '/root/0000/00/Debug/dbnet5.0' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Microsoft.DotNet.CommandFactory.ProjectFactory.GetMSBuildProjPath(String projectDirectory)
   at Microsoft.DotNet.CommandFactory.ProjectFactory.GetMSBuildProj(String projectDirectory, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.CommandFactory.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

`

`try
{
if (conn.State != ConnectionState.Open)
{
conn.Open();
}
CacheCommand cmd = new CacheCommand();
cmd.Connection = this.conn;
if (inTransaction)
cmd.Transaction = trans;
DataSet ds = new DataSet();
CacheDataAdapter ad = new CacheDataAdapter();
cmd.CommandText = QueryString;
//CLogger._log.Debug(QueryString);
ad.SelectCommand = cmd;
ad.Fill(ds);
ad.Dispose();
return ds;
}
catch (Exception e2)
{
throw e2;
}`

can anyone hava a look for this?

**Comment by dyubaylo97** [comment]
hello,
Please ask such question on InterSystems Developer Community: https://community.intersystems.com.
If you have any problem to create a post on DC, please let us know.

Thank you!
